# Generated by Django 5.0.3 on 2024-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(default='', to='Music.genre'),
        ),
    ]
