# Generated by Django 5.0.3 on 2024-04-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_track_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(default=list, to='Music.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(default=list, to='Music.genre'),
        ),
        migrations.AlterField(
            model_name='extendedplaylist',
            name='genres',
            field=models.ManyToManyField(default=list, to='Music.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Music.genre'),
        ),
    ]
