# Generated by Django 5.0.3 on 2024-04-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_remove_artist_sign_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
