# Generated by Django 5.0.3 on 2024-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.JSONField(default=list),
        ),
    ]
