# Generated by Django 5.0.3 on 2024-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_alter_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.JSONField(default=list),
        ),
    ]
