# Generated by Django 5.0.3 on 2024-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_remove_artist_genres_alter_genre_genre_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
