# Generated by Django 5.0.3 on 2024-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_appuser_date_joined_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.JSONField(default=''),
        ),
    ]
