# Generated by Django 5.0.3 on 2024-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_alter_track_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(limit_choices_to=3, related_name='artists', to='Music.genre'),
        ),
    ]
