# Generated by Django 5.0.3 on 2024-05-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_remove_artist_genres_alter_genre_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
    ]
