# Generated by Django 5.0.3 on 2024-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_remove_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='Music.genre'),
        ),
    ]
