# Generated by Django 5.0.3 on 2024-05-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
