# Generated by Django 5.0.3 on 2024-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_alter_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.CharField(blank=True, default=list, max_length=100),
        ),
    ]
