# Generated by Django 5.0.3 on 2024-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0014_remove_artist_biography_remove_artist_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
