# Generated by Django 5.0.3 on 2024-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0015_alter_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
