# Generated by Django 5.0.3 on 2024-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0017_alter_artist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(default=list, to='Music.genre'),
        ),
    ]
