# Generated by Django 5.0.3 on 2024-05-05 22:43

import Music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0018_remove_artist_genres_artist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.JSONField(default=list, verbose_name=Music.models.Genre),
        ),
    ]
