# Generated by Django 5.0.3 on 2024-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0021_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.BinaryField(),
        ),
    ]
